a = str(input("enter your name."))
b = input("enter your loved one name.")
c = a.lower()
d = b.lower()
f = str(c) + str(d)
g = f.count("t")
h = f.count("r")
i = f.count("u")
j = f.count("e")
k = f.count("l")
l = f.count("o")
m = f.count("v")
n = f.count("e")
o = str(g + h + i + j)
p = str(k + l + m + n)
q = int(o + p)
if q <= 10:
    print(f"your love score is {q}%")
    print("one sided")
elif q > 90:
    print(f"your love score is {q}%")
    print("made for each other.")
else:
    print(f"your love score is {q}%")
